auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# --- Fixed compactor section ---
compactor:
  working_directory: /tmp/loki/compactor
  retention_enabled: true
  delete_request_store: boltdb-shipper  # <-- FIX 1: Added this line

limits_config:
  retention_period: 1440h # 60 days * 24 hours = 1440 hours
  allow_structured_metadata: false   # <-- FIX 2: Added this line
# --- End of retention section ---