server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Drop noisy containers (loki, promtail, grafana)
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(loki|promtail|grafana)"
        action: drop

      # Add identifying labels for Loki
      - source_labels: ["__meta_docker_container_name"]
        target_label: "container"
      - source_labels: ["__meta_docker_image"]
        target_label: "image"
      - target_label: "job"
        replacement: "docker"    # Static job label
      - target_label: "host"
        replacement: "local"     # Optional: useful if you later add multiple nodes

      # Path to actual container log file
      - source_labels: ["__meta_docker_container_id"]
        target_label: "__path__"
        replacement: "/var/lib/docker/containers/$1/$1-json.log"

    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
      - output:
          source: log

      # Extract log level from Loguru or Uvicorn format
      - regex:
          expression: '.*\| (?P<level>\w+)\s+\|.*'
      - labels:
          level:

      # Drop DEBUG logs
      - drop:
          source: "level"
          value: "DEBUG"

      # Drop Uvicorn health checks
      - drop:
          expression: ".*(GET /health|GET /ready|GET /metrics).*"
