scrape_configs:
  - job_name: docker
    static_configs: []  # keep structure clean
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Drop noisy containers
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(loki|promtail|grafana)"
        action: drop

      # Attach container name and image as labels
      - source_labels: ["__meta_docker_container_name"]
        target_label: "container"
      - source_labels: ["__meta_docker_image"]
        target_label: "image"

      # Where logs are stored
      - source_labels: ["__meta_docker_container_id"]
        target_label: "__path__"
        replacement: "/var/lib/docker/containers/$1/$1-json.log"

    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
      - output:
          source: log
      - regex:
          expression: '.*\| (?P<level>\w+)\s+\|.*'
      - labels:
          level:
      - drop:
          source: "level"
          value: "DEBUG"
      - drop:
          expression: ".*(GET /health|GET /ready|GET /metrics).*"
