"""uix id provider

Revision ID: 2724092e2bf1
Revises: aac314c44dc6
Create Date: 2025-08-23 02:57:13.234516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2724092e2bf1'
down_revision: Union[str, Sequence[str], None] = 'aac314c44dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_id_provider', 'provider', ['provider_id', 'provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_id_provider', 'provider', type_='unique')
    # ### end Alembic commands ###
