"""added email based invite

Revision ID: 49ace85c276e
Revises: 912ed6f3728a
Create Date: 2025-11-30 04:32:14.181975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '49ace85c276e'
down_revision: Union[str, Sequence[str], None] = '912ed6f3728a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_invite', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_invite', 'email')
    # ### end Alembic commands ###
