"""added last_read_message_id

Revision ID: 4d7abf76ac3b
Revises: d5059fb93c7c
Create Date: 2025-08-21 07:23:10.920883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4d7abf76ac3b'
down_revision: Union[str, Sequence[str], None] = 'd5059fb93c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_member', sa.Column('last_read_message_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'chat_member', 'message', ['last_read_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_member', type_='foreignkey')
    op.drop_column('chat_member', 'last_read_message_id')
    # ### end Alembic commands ###
