"""added tags

Revision ID: 53c2c060ad1c
Revises: 028f05ed952f
Create Date: 2025-08-25 09:43:13.720625

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53c2c060ad1c"
down_revision: Union[str, Sequence[str], None] = "028f05ed952f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tag_name"), "tag", ["name"], unique=False)
    op.create_index(op.f("ix_tag_usage_count"), "tag", ["usage_count"], unique=False)
    op.create_table(
        "course_tags",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("course_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("course_id", "tag_id"),
    )
    op.create_index(
        "idx_course_tags_lookup", "course_tags", ["course_id", "tag_id"], unique=False
    )
    # op.alter_column('chat', 'course_id',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Uuid(),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column(
    #     "chat",
    #     "course_id",
    #     existing_type=sa.Uuid(),
    #     type_=sa.VARCHAR(),
    #     existing_nullable=True,
    # )
    op.drop_index("idx_course_tags_lookup", table_name="course_tags")
    op.drop_table("course_tags")
    op.drop_index(op.f("ix_tag_usage_count"), table_name="tag")
    op.drop_index(op.f("ix_tag_name"), table_name="tag")
    op.drop_table("tag")
    # ### end Alembic commands ###
