"""updates on model

Revision ID: 666e7c9b0955
Revises: 7960acc7412e
Create Date: 2025-11-24 11:41:36.485780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '666e7c9b0955'
down_revision: Union[str, Sequence[str], None] = '7960acc7412e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('last_message_at', sa.DateTime(), nullable=False))
    op.add_column('chat_member', sa.Column('is_creator', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_member', 'is_creator')
    op.drop_column('chat', 'last_message_at')
    # ### end Alembic commands ###
