"""model update comment likes

Revision ID: 85ef3559b172
Revises: 6017061a2e0c
Create Date: 2025-09-09 20:02:49.987699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '85ef3559b172'
down_revision: Union[str, Sequence[str], None] = '6017061a2e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentlike',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'comment_id', name='uix_account_comment')
    )
    op.create_index(op.f('ix_commentlike_account_id'), 'commentlike', ['account_id'], unique=False)
    op.create_index(op.f('ix_commentlike_comment_id'), 'commentlike', ['comment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commentlike_comment_id'), table_name='commentlike')
    op.drop_index(op.f('ix_commentlike_account_id'), table_name='commentlike')
    op.drop_table('commentlike')
    # ### end Alembic commands ###
