"""added embed_url_for_video creation

Revision ID: 98606b4368be
Revises: fc9c2d771a1a
Create Date: 2025-09-20 09:47:45.161588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '98606b4368be'
down_revision: Union[str, Sequence[str], None] = 'fc9c2d771a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_content', sa.Column('embed_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_content', 'embed_url')
    # ### end Alembic commands ###
