"""provider costraint

Revision ID: aac314c44dc6
Revises: 4d7abf76ac3b
Create Date: 2025-08-22 17:01:49.465075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aac314c44dc6'
down_revision: Union[str, Sequence[str], None] = '4d7abf76ac3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_account_provider', 'provider', ['account_id', 'provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_account_provider', 'provider', type_='unique')
    # ### end Alembic commands ###
