"""corrected relationships

Revision ID: c286c6343233
Revises: 53c2c060ad1c
Create Date: 2025-08-27 14:59:44.782934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c286c6343233'
down_revision: Union[str, Sequence[str], None] = '53c2c060ad1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('is_rating', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'is_rating')
    # ### end Alembic commands ###
