"""last_module

Revision ID: d785f59daf19
Revises: f1ea2a1472e6
Create Date: 2025-10-07 18:36:21.753863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd785f59daf19'
down_revision: Union[str, Sequence[str], None] = 'f1ea2a1472e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_progress', sa.Column('next_module', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('course_progress', sa.Column('next_section', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_progress', 'next_section')
    op.drop_column('course_progress', 'next_module')
    # ### end Alembic commands ###
