"""encrypted tokens

Revision ID: fc9c2d771a1a
Revises: 85ef3559b172
Create Date: 2025-09-12 06:15:05.595994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc9c2d771a1a'
down_revision: Union[str, Sequence[str], None] = '85ef3559b172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_attachment', sa.Column('document_type', sa.Enum('GOOGLE_DRIVE', 'DROPBOX', 'ONEDRIVE', 'DIRECT_LINK', name='documentplatform'), nullable=True))
    op.add_column('module_attachment', sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('provider', sa.Column('access_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('provider', sa.Column('refresh_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('provider', 'access_token')
    op.drop_column('provider', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('provider', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('provider', 'refresh_token_encrypted')
    op.drop_column('provider', 'access_token_encrypted')
    op.drop_column('module_attachment', 'file_type')
    op.drop_column('module_attachment', 'document_type')
    # ### end Alembic commands ###
